baseURL = "http://davidayala.eu/ssg-huguoc/"
languageCode = "ca-es"
title = "UOC Static Site Generator"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

[params]
  projectDir = "/ssg-huguoc"
